/**
 * Prebuild content check. Runs with no env values set.
 *  - Fails if a live route renders a non-verified metric, testimonial, case study or client logo.
 *  - Fails if nav links point at routes that do not exist.
 *  - Fails if banned claims or tools appear in source files.
 * `--write-todo` regenerates CONTENT_TODO.md.
 */
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";
import { proof } from "../content/proof";
import { legalRoutes, liveRoutes, navRoutes } from "../lib/routes";

const root = process.cwd();
const live = new Set<string>(liveRoutes);
const errors: string[] = [];

type Item = { id: string; status: string; routes: string[]; kind: string };
const items: Item[] = [
  ...proof.caseStudies.map((i) => ({ ...i, kind: "case study" })),
  ...proof.metrics.map((i) => ({ ...i, kind: "metric" })),
  ...proof.testimonials.map((i) => ({ ...i, kind: "testimonial" })),
  ...proof.clientLogos.map((i) => ({ ...i, kind: "client logo" })),
];

for (const it of items) {
  const published = it.routes.filter((r) => live.has(r));
  if (it.status !== "verified" && published.length) {
    errors.push(`${it.kind} "${it.id}" is ${it.status} but renders on ${published.join(", ")}`);
  }
}
for (const r of [...navRoutes, ...legalRoutes]) {
  if (!live.has(r.href)) errors.push(`Nav links to "${r.href}", which is not a live route`);
}

const banned: [RegExp, string][] = [
  [/\bAWS\b/i, "AWS"],
  [/kubernetes|\bk8s\b/i, "Kubernetes"],
  [/kafka/i, "Kafka"],
  [/lorem ipsum/i, "lorem ipsum"],
  [/fortune 500/i, "Fortune 500"],
];
function walk(dir: string): string[] {
  return readdirSync(dir).flatMap((f) => {
    const p = join(dir, f);
    return statSync(p).isDirectory() ? walk(p) : /\.(tsx?|md)$/.test(f) ? [p] : [];
  });
}
for (const dir of ["app", "components", "content", "lib"]) {
  for (const file of walk(join(root, dir))) {
    const text = readFileSync(file, "utf8");
    for (const [re, label] of banned) {
      if (re.test(text)) errors.push(`${relative(root, file)} mentions banned term: ${label}`);
    }
  }
}

if (process.argv.includes("--write-todo")) {
  const fills: string[] = [
    "Set NEXT_PUBLIC_SITE_URL (https://www.elssoftwaresolutions.co.ke) and NEXT_PUBLIC_CONTACT_EMAIL in Vercel project env vars; values are in .env.example",
    "Contact email is a personal Gmail address. Consider a business address on the domain before launch",
    "WhatsApp Business number, digits only (NEXT_PUBLIC_WHATSAPP_NUMBER): WhatsApp buttons are omitted until set",
    "GitHub and X URLs in content/site.config.ts: omitted until set (LinkedIn is set)",
    "GA4 measurement ID (NEXT_PUBLIC_GA4_ID): no analytics or consent banner until set",
    "Resend: RESEND_API_KEY, RESEND_FROM (address on a verified sending subdomain), LEAD_NOTIFY_TO. Without a lead sink in production, forms tell visitors to email or WhatsApp",
    "Optional: SHEETS_WEBHOOK_URL, Turnstile keys, Upstash Redis URL and token",
    "Production stack list: confirm each tool is true before it appears on a page (Go/Gin/sqlc/pgx, FastAPI, Next.js, PostgreSQL RLS, Redis, WebSockets, M-Pesa Daraja, Cloud Run/Cloud SQL/BigQuery/Pub/Sub, Docker, GitHub Actions, Groq/OpenAI-compatible APIs). Not published yet",
    "Logo: built from the supplied JPEG (transparent PNG variants in public/brand/). Replace with an SVG master when available",
    "/privacy and /terms: draft, pending legal review. Check the 12-month retention period, the Kenyan governing-law clause, and add the ODPC registration line only if registered",
    "Contact form budget ranges are in USD and are my default choice. Change in lib/validation.ts if you prefer KES",
    "Copy written by the build (funnel step notes, construction page discovery text, FAQ answers): review before launch",
  ];
  const unverified = items.filter((i) => i.status !== "verified");
  const md = [
    "# CONTENT_TODO",
    "",
    "Generated by `npm run content:todo`. Edit the sources, not this file.",
    "",
    "## [FILL] values",
    ...fills.map((f) => `- [ ] ${f}`),
    "",
    "## Unverified items",
    ...(unverified.length
      ? unverified.map((i) => `- [ ] ${i.kind} \`${i.id}\` (${i.status})`)
      : ["- None. No case studies, metrics, testimonials or client logos exist yet, so those sections are omitted."]),
    "",
    "## Never publish without verification",
    "- Client names, logos, testimonials, case studies, outcome metrics",
    "- Projects delivered, years of experience, industries served, training hours, team size",
    "- Mezani marketing figures and sample dashboard numbers",
    "- AWS, Kubernetes, Kafka",
    "",
  ].join("\n");
  writeFileSync(join(root, "CONTENT_TODO.md"), md);
  console.log("CONTENT_TODO.md written");
}

if (errors.length) {
  console.error("Content check failed:\n" + errors.map((e) => `  - ${e}`).join("\n"));
  process.exit(1);
}
console.log(`Content check passed (${items.length} proof items, ${live.size} live routes).`);
